# Generated by Django 5.2.4 on 2025-07-17 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_bus_cab_holiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('netbanking', 'Net Banking'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(default='Success', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
