# Generated by Django 5.2.4 on 2025-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_booking_room_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/holidays/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/rooms/'),
        ),
    ]
