# Generated by Django 5.2.4 on 2025-07-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flight'),
        ),
    ]
